# Generated by Django 2.2 on 2019-04-10 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_auto_20190409_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=20)),
                ('tartget_object_id', models.PositiveIntegerField()),
                ('action_object_id', models.PositiveIntegerField()),
                ('action_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activiylog_action', to='contenttypes.ContentType')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activiylog_target', to='contenttypes.ContentType')),
            ],
        ),
    ]
