# Generated by Django 2.2 on 2019-04-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_boardactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardactivitylog',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
    ]
