# Generated by Django 2.2 on 2019-04-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_boardactivitylog_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardactivitylog',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
    ]
