# Generated by Django 2.2 on 2019-04-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190410_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
