# Generated by Django 2.2 on 2019-04-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_list_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
