# Generated by Django 2.2 on 2019-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20190411_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
