# Generated by Django 2.2 on 2019-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('color', 'board', 'text')},
        ),
    ]
