# Generated by Django 2.2 on 2019-04-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20190416_0658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('color', 'board'), ('text', 'board')},
        ),
    ]
