# Generated by Django 2.2 on 2019-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20190416_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='boards.Label'),
        ),
    ]
